version: "3"

services:
#  db:
#    image: mariadb:5.5
#    volumes:
#      - "./mysql:/var/lib/mysql:rw"
#    env_file:
#      - .env
#    ports:
#      - "3306:3306"
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
#      - /Users/IdeaProjects/home:/var/www/home # mac
      - /E/Develop/projects/docker-web:/var/www/home # windows
#    command: /usr/sbin/sshd -D
    ports:
      - "80:80"
#      - '11111:22'
#    expose:
#      - '11111'
